// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCPoB6gWLrbp9whpbRisW5H-wFfv76iJU',
    appId: '1:595841032638:web:2356b1aebd60da860b59ef',
    messagingSenderId: '595841032638',
    projectId: 't-variety-362021',
    authDomain: 't-variety-362021.firebaseapp.com',
    storageBucket: 't-variety-362021.appspot.com',
    measurementId: 'G-M17DTHNFNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIRvEMYyUtODz3bXX3HzH3Sh69EckZJQ',
    appId: '1:595841032638:android:c72629977ad74cfa0b59ef',
    messagingSenderId: '595841032638',
    projectId: 't-variety-362021',
    storageBucket: 't-variety-362021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8g6tpfhVH9Nxf0YMaztl6c-y0sq2UOpU',
    appId: '1:595841032638:ios:c8d8a319fa8a20190b59ef',
    messagingSenderId: '595841032638',
    projectId: 't-variety-362021',
    storageBucket: 't-variety-362021.appspot.com',
    iosClientId: '595841032638-gei4kcv9h80qah7p65a88hlmi1f4evm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDddWithCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8g6tpfhVH9Nxf0YMaztl6c-y0sq2UOpU',
    appId: '1:595841032638:ios:c8d8a319fa8a20190b59ef',
    messagingSenderId: '595841032638',
    projectId: 't-variety-362021',
    storageBucket: 't-variety-362021.appspot.com',
    iosClientId: '595841032638-gei4kcv9h80qah7p65a88hlmi1f4evm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDddWithCubit',
  );
}
